### PR TITLE
Add color picker, draggable rows, and delete icon

### PR DESCRIPTION
**Pull request by stefansundin**
I hope you don't think I changed too much in one go. I separated the changes into two commits to make it easier to view the code I actually changed. I added a nice section in the README to help verify that dependencies are correct.

I changed the manifest description because it's not only for cross-account access. It's also very useful to just access different roles in the same account.

I hope you like it!

### CODE REVIEW

**Comment by stefansundin** [comment]
We should probably work out a better default color palette. Some of the colors on the default palette do not look all that great. The documentation for the color picker is here: https://bgrins.github.io/spectrum/

**Comment by derBroBro** [comment]
Thank you very much, looks great!

**Comment by derBroBro** [comment]
I checked the changes and would like to fix the following:  
- Change the height to 300px
- Change the color column to 60px to prevent the spectre line break

What to you think?

**Comment by stefansundin** [comment]
- I increased the popup height to fit the color picker for the bottom most entry. I want them all to drop the picker the same direction. I think the picker drops in awkward ways if the height is 300px.
- I'm not exactly sure what the color column is?

**Comment by derBroBro** [comment]
- Yes you are right, this makes sense.
- If I leave the color column at the default value it looks like this:
  image

**Comment by stefansundin** [comment]
Oh, I see. Yes, go ahead, change it.

It doesn't look like that on my computer, but I've only tested on Mac.

screen shot 2016-09-16 at 9 26 18 am

**Comment by stefansundin** [comment]
We can use the empty bottom space to have "saved entries", like I mentioned in issue #1. But I will look into that when I have the need for it. I think these changes are enough for a new release.

**Comment by derBroBro** [comment]
ok, uploaded. Should we available within the next hours.

**Pull request merged**
